title: 'Steve Oliver'
description: 'Web developer, Drupal Commerce specialist'
theme: jekyll-theme-architect
github:
  is_user_page: true
  is_project_page: false
google:
  fonts: Open+Sans|Oswald|Saira+Extra+Condensed
  analytics: 'UA-15224036-2'
